Awit 88 stworzyc api do watkow
pploszczyca/AwITeks pull request #60
Opened 2022-05-18 17:51 UTC by bszlacht

Implemented forum on backend
Includes tickets:  AWIT-84 i AWIT 85

2022-05-18 20:28 UTC, pploszczyca requested changes
Trzeba parę rzeczy poprawić

2022-05-18 20:28 UTC, pploszczyca commented on backend/src/main/java/pl/edu/agh/awiteks_backend/models/ForumThread.java
> +    private final LocalDateTime creationTime = LocalDateTime.now();
Skoro dodaliście nowe pola do modelu, to należy zaktualizować plik `gen-test-data.sql`, w którym jest przykład bazy danych, aby można było z tego korzystać

2022-05-18 20:28 UTC, pploszczyca commented on backend/src/main/java/pl/edu/agh/awiteks_backend/models/ForumThread.java
> +        return null;
To chyba nie jest potrzebne

2022-05-18 20:28 UTC, pploszczyca commented on backend/src/main/java/pl/edu/agh/awiteks_backend/models/User.java
> +//    }
To trzeba usunąć, bo jest niepotrzebne

2022-05-18 20:28 UTC, pploszczyca commented on backend/src/main/java/pl/edu/agh/awiteks_backend/models/User.java
> +    }
Pasuje usunąć ten komentarz i dodać komentarz z `TODO`, dlaczego jest to zharddkorowane

2022-05-18 20:28 UTC, pploszczyca commented on backend/src/main/java/pl/edu/agh/awiteks_backend/services/ForumService.java
> +        return this.streamUtilities.asStream(forumRepository.findAll()).map(ForumMapper::mapForumThreadToForumThreadSummary).collect(Collectors.toList());
Zamiast `.collect(Collectors.toList())` wystarczy samo `.toList()`

2022-05-18 20:28 UTC, pploszczyca commented on backend/src/main/java/pl/edu/agh/awiteks_backend/services/ForumService.java
> +//    }
Jak tego kodu nie używamy, to do wywalenia

2022-05-18 20:28 UTC, pploszczyca commented on backend/src/main/java/pl/edu/agh/awiteks_backend/services/ForumService.java
> +    }
Skoro ta metoda nie jest nigdzie używana, to można ją wyrzucić

2022-05-18 20:28 UTC, pploszczyca commented on backend/src/main/java/pl/edu/agh/awiteks_backend/services/ForumService.java
> +    public Optional<ForumThread> get(int id, int userId) {
`userId` nie jest nigdzie wykorzystywany

2022-05-18 20:28 UTC, pploszczyca commented on backend/src/main/java/pl/edu/agh/awiteks_backend/api/forum/ForumController.java
> +                                                             JwtAccessToken jwtAccessToken) {
`favOnly`, `ownOnly` i `jwtAccessToken` nie są używane, można wyrzucić

2022-05-18 20:28 UTC, pploszczyca commented on backend/src/main/java/pl/edu/agh/awiteks_backend/services/ForumService.java
> +        return thread.getForumPosts();  // todo ???
Co oznacza to `TODO`?

2022-05-18 20:28 UTC, pploszczyca commented on backend/src/main/java/pl/edu/agh/awiteks_backend/services/ForumService.java
> +        creator.getForumPostList().add(post);//Maybe?
Jaki problem?

2022-05-18 20:28 UTC, pploszczyca commented on backend/src/main/java/pl/edu/agh/awiteks_backend/api/forum/ForumController.java
> +    public List<ForumPost> getPostsFromThread(@PathVariable int threadId, JwtAccessToken jwtAccessToken) {
`jwtAccessToken` tutaj również jest zbędny

2022-05-18 20:28 UTC, pploszczyca commented on backend/src/main/java/pl/edu/agh/awiteks_backend/api/forum/ForumController.java
> +    public List<ForumThreadSummaryResponseBody> getThreadsWithMatchingName(@RequestParam(name = "keyword", defaultValue = "") String searchKey, JwtAccessToken jwtAccessToken){
Dwie sprawy
1. `name` w `@RequestParam` powinno mieć taką samą nazwę jak zmienna, czyli `searchKey`
2. `jwtAccessToken` nie jest nigdzie używane, do wyrzucenia

2022-05-18 20:28 UTC, pploszczyca commented on backend/src/main/java/pl/edu/agh/awiteks_backend/api/forum/ForumController.java
> +        return forumService.getThreadsWithMatchingName(searchKey);   //TODO: Does not work, returns all. What?
Działa, tylko pewnie złego headera robiliście w zapytaniu, bo wg tego kodu, to w headerze trzeba podać `keyword` zamiast `searchKey`

2022-05-18 20:28 UTC, pploszczyca commented on backend/src/main/java/pl/edu/agh/awiteks_backend/services/ForumService.java
> +        return this.getAllThreads().stream().filter(thread -> thread.title().contains(searchKey)).collect(Collectors.toList());
Dwie sprawy:
1. Dobrze, żeby `title` i `searchKey` były porównywane za pomocą małych liter, bo wtedy łatwiej będzie coś znaleźć. Wystarczy na obydwu zmiennych użyć `.toLowerCase()`
2. Zamiast `.collect(Collectors.toList())` można użyć `.toList()`

2022-05-19 16:46 UTC, kkoz3434 commented
Że tak pozwolę sobie zapytać: Czemu nie zrobiliście osobnych branchy dla konkretnych zadań? Z tego co rozmawialiśmy na zajęciach 1 branch == 1 task. Nie pierwsza już taka sytuacja, gdzie jest bałagan na branchach. Smutczek :c

2022-05-20 11:40 UTC, bszlacht commented
> Że tak pozwolę sobie zapytać: Czemu nie zrobiliście osobnych branchy dla konkretnych zadań? Z tego co rozmawialiśmy na zajęciach 1 branch == 1 task. Nie pierwsza już taka sytuacja, gdzie jest bałagan na branchach. Smutczek :c
Sory, w sensie troche za bardzo rozdrobnione to było i nawet nie wiedzielismy ze sa osobne taski na te rzeczy

2022-05-23 14:08 UTC, pploszczyca requested changes
Dwie sprawy:
1. Jak coś zostało poprawione, to należy rozwiązać konwersacje, bo wtedy wiadomo, co zostało zrobione.
2. Wywala testy na backendzie związane z Checkstyle, trzeba odpowiednio sformatować kod, żeby testy przechodziło

2022-05-23 14:08 UTC, pploszczyca commented on backend/src/main/java/pl/edu/agh/awiteks_backend/services/ForumService.java
> +    }
Z tego co widzę, ta metoda nie jest nigdzie używana i można ją usunąć, jak pisałem wcześniej

2022-05-23 14:08 UTC, pploszczyca commented on backend/src/main/java/pl/edu/agh/awiteks_backend/services/ForumService.java
> +    }
Ja tego nie widzę, ale chyba tutaj nie ma zrobionej walidacji, tzn. nie sprawdzamy, czy osoba, która edytuje `Thread`, należy do niego

2022-05-24 08:46 UTC, pploszczyca approved these changes
Ok

2022-05-24 08:49 UTC, bszlacht reviewed
good

2022-05-24 08:49 UTC, merged